### ISSUE TITLE
Logged out immediately after logging in

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#176]
<a href="https://github.com/typhoon2099"><img src="https://avatars0.githubusercontent.com/u/828104?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [typhoon2099](https://github.com/typhoon2099)**
_Thursday Apr 05, 2018 at 12:03 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/70_

----

I'm still not sure if I've configured Auth0 correctly. I've checked the Auth0 logs and appear to be getting a failed silent auth on the login page, after which I can log in, but I don't get to do anything before I've been logged out by the frontend. Auth0 logs it as a successful logout.

I notice when I'm on the homepage that /api/manager/public/region returns a 404 (message: Unknown error occurred), could this be causing the frontend to panic and kick me out?

Just to note: I'm using the `auth0-update-sql` branch as I can't get Auth0 to work on the dev branch (hard coded URLs etc).

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Nov 13, 2018 at 19:01 GMT_

----

I believe this should be solved with #250 now.

**Comment by gelinger777** [comment]
@landonreed  I have still have this issue on master branch. 
Failed Silent Auth .

**Comment by landonreed** [comment]
@gelinger777, did you happen to see/follow @karimhm's final comments on https://github.com/ibi-group/datatools-ui/issues/441#issuecomment-497459261

**Comment by gelinger777** [comment]
@landonreed  that fixed the issue with logging in, but still I have this 

![image](https://user-images.githubusercontent.com/184276/64742719-7c602180-d4fd-11e9-9fd8-0355c2f6d538.png)

**Comment by gelinger777** [comment]
@landonreed  yes, that was the reason. It's fixed. thank u
